### ISSUE TITLE
Enable binary compatibility

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-chatbots#46]
Once 1.0.0 is out, we need to enable binary compatibility by removing this

https://github.com/micronaut-projects/micronaut-chatbots/blob/c2c23e3c5fa143b99a0629f27e9e3ef0b4b313ab/buildSrc/src/main/groovy/io.micronaut.build.internal.chatbots-module.gradle#L12-L16

**Comment by sdelamo** [comment]
@timyates can this be closed? If it can, close it.

**Comment by timyates** [comment]
Done in https://github.com/micronaut-projects/micronaut-chatbots/pull/169
